### ISSUE TITLE
Polymorphisms not visible in small numbers

### ISSUE THREAD

**Issue by jaw-jaw** [pbnjay/lollipops#27]
Hi, when I have 2 variants at the same locus, small numbers are not visibly different from a single variant. Is there any way to force lollipops to stack identical variants the way it does when they're very close to each other? 

Eg, in the command+image below, there is 1 variant at 610, 2 at 629, and 5 at 655, but the first loci have identical icons, and the the third is barely larger. Changing the DPI still makes the icons hard to discern by eye. I'd rather stack variants like the three at 554-556.

Thanks heaps!

lollipops -o=example.png Q16853 554#ae2727 555#ae2727 556#ae2727 610#ae2727 629#ae2727@2 655#ae2727@5

![example](https://user-images.githubusercontent.com/32260937/30800789-16a0f67a-a1d9-11e7-8de5-e8ec99d927fb.png)

**Comment by pbnjay** [comment]
You're only providing positions in your inputs, so the tool has no way of knowing this represents 2 variants. For example if you put "P629A P629B" instead of "629@2" it will show them stacked.

The @ numbers are intended for population counts (e.g. 100 patients had the X variant vs 20 patients had the Y variant) - they're just arbitrary scaling factors for the pop's surface area, so you can make them whatever you want to allow you to better distinguish features. At low resolution and low counts you won't see much difference.
