### ISSUE TITLE
how to add a local .json file, and where to put it.

### ISSUE THREAD

**Issue by tcjacob** [pbnjay/lollipops#31]
I've had trouble getting the lollipop to run with my local.json file (since the uniprot isn't accurate enough and I want to add other domains). Here are the two examples I've tried. Note, the tcjtest2 file is stored on the desktop - I don't know if this is part of the problem. 
Thanks, TCJ!
tcjtest2.json file tests 
lollipops.exe -legend -l tcjtest2.json S2G#ff0000@3 S2G#ff0000@2 S3P#ff0000@1 P4L#ff0000@20 

lollipops.exe -legend -l=tcjtest2.json S2G#ff0000@3 S2G#ff0000@2 S3P#ff0000@1 P4L#ff0000@20 
 below is the code for tcjtest2.json, which works fine at pfam in the code generator window
{
  "length" : "534",
  "regions" : [
    {
      "type" : "pfama",
      "text" : "Peptidase_S8",
      "colour" : "#2dcfff",
      "display": "true",
      "startStyle" : "curved",
      "endStyle" : "curved",
      "start" : "159",
      "end" : "361",
      "aliEnd" : "350",
      "aliStart" : "163"
    },
    {
      "type" : "pfama",
      "text" : "PA",
      "colour" : "#ff5353",
      "display" : true,
      "startStyle" : "jagged",
      "endStyle" : "curved",
      "start" : "388",
      "end" : "469",
      "aliEnd" : "469",
      "aliStart" : "396"
    }
  ]
}

**Comment by pbnjay** [comment]
First, I think you need to include the gene symbol as the first argument (it uses this for the output filename).

Otherwise, it should work if tcjtest2.json is in the same folder as lollipops.exe, or if you give the full path to the file e.g. "C:\Users\yourusername\Desktop\tcjtest2.json" (you may have to put that in double quotes if there are spaces).

You should be running it from a command prompt / powershell, if you're not I don't know how to help. Sorry I haven't used Windows very much in years....
