### ISSUE TITLE
Binary for windows

### ISSUE THREAD

**Issue by roys911** [pbnjay/lollipops#8]
Thank you for providing this great tool. for the most recent release do you have binaries for windows? I tried compiling from source code but I am getting the following error

C:\Users\roys\Downloads\lollipops-0.96\lollipops-0.96>go build main.go
command-line-arguments
.\main.go:33: undefined: GetProtID
.\main.go:51: undefined: GetPfamGraphicData
.\main.go:73: undefined: DrawSVG

here are the list of files from source.zip
01/14/2015  03:01 PM            11,754 drawpops.go
01/14/2015  03:01 PM             2,863 fetch_data.go
01/14/2015  03:01 PM             1,359 fonts.go
01/14/2015  03:01 PM             1,541 main.go
01/14/2015  03:01 PM             2,639 README.md
01/14/2015  03:01 PM            13,305 tp53.png
01/14/2015  03:01 PM             6,256 tp53.svg
01/14/2015  03:01 PM            18,092 tp53_more.png

If there are specific instructions to compile in windows, it will be helpful.
Thank you!

**Comment by pbnjay** [comment]
With the command `go build main.go` you're only compiling 1/4 files. You should use `go build .` (i.e. a dot instead of main.go) - that'll use all the files in the folder. If you haven't made changes to the code, it'll be much easier to just use `go get github.com/pbnjay/lollipops` to install an .exe for you though (into `$GOPATH/bin/lollipops` or whatever the equivalent is for windows).

If you are making changes to the code, then I highly recommend reading more about Go before diving in, specifically the language docs and "Effective Go" for more information on how to get started.

**Comment by roys911** [comment]
Thank you! It worked.
